# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice Workspace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice Workspace

  target 'Practice WorkspaceTests' do
    inherit! :search_paths
    # Pods for testing
pod 'SnapKit', '~> 5.0.0'
  end

  target 'Practice WorkspaceUITests' do
    # Pods for testing
  end

end
